### ISSUE TITLE
Can't update/sync group with certain OU

### ISSUE THREAD

**Issue by Mugulane** [jay0lee/GAM#104]
I got this error when i wanted to sync group with certain OU.

user@hostname:~$ gam update group group@domainname.ee sync member ou_and_children "ou-name-and-its-children"

Getting all users in the Google Apps organization (may take some time on a large domain)...
Got 340 users..
done.
Got 367 members... group@domainname.ee (may take some time for large groups)...
Traceback (most recent call last):
  File "/home/user/gam/gam.py", line 8258, in <module>
    doUpdateGroup()
  File "/home/user/gam/gam.py", line 5194, in doUpdateGroup
    current_emails = getUsersToModify(entity_type=u'group', entity=group, member_type=role)
  File "/home/user/gam/gam.py", line 7772, in getUsersToModify
    users.append(member[u'email'])
KeyError: u'email'

What should be the problem? 

client_secret and oauth files seem to be in order also.

**Comment by Mugulane** [comment]
still same with different lines:
------------
Traceback (most recent call last):
  File "/home/user/gam/gam.py", line 8700, in <module>
    doUpdateGroup()
  File "/home/user/gam/gam.py", line 5566, in doUpdateGroup
    current_emails = getUsersToModify(entity_type=u'group', entity=group, member_type=role)
  File "/home/andrus/gam/gam.py", line 8192, in getUsersToModify
    users.append(member[u'email'])
KeyError: u'email'

i have installed the newest GAM. UTF-8 fix should've worked by now.

**Comment by Mugulane** [comment]
Works with v3.7.
Nice! Thanks!
