### ISSUE TITLE
Issue with GAM 4.96

### ISSUE THREAD

**Issue by RomainB91** [jay0lee/GAM#1041]
Hi,

Thanks for creating GAM !

I've recently upgraded to GAM 4.96, but now i have a strange issue : 

When i'm using the gam command : "gam print users Email Aliases Fullname Firstname Lastname OU Suspended LastLoginTime > test.csv".

And here is the strange error i get : 

"Traceback (most recent call last):
  File "C:\Users\travis\build\jay0lee\GAM\src\gam.py", line 14989, in <module>
  File "C:\Users\travis\build\jay0lee\GAM\src\gam.py", line 14477, in ProcessGAMCommand
  File "C:\Users\travis\build\jay0lee\GAM\src\gam.py", line 11770, in doPrintUsers
  File "C:\Users\travis\build\jay0lee\GAM\src\gam.py", line 11501, in writeCSVfile
  File "C:\Python38\lib\csv.py", line 157, in writerows
  File "C:\Python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0141' in position 32: character maps to <undefined>
[7396] Failed to execute script gam".

I don't understand this message, because : 
1. There is not "travis" user on my Windows computer.
2. There is not "c:\Python38" folder on my computer.

So i'm a little bit surprised by this error.
Please could you help me ?

Best regards.

**Comment by RomainB91** [comment]
I'm just rolling back to GAM 4.61 and all work fine now.
