### ISSUE TITLE
Error when trying to print all cros

### ISSUE THREAD

**Issue by tmulroy1** [jay0lee/GAM#1054]
I'm receiving an error when trying to print all cros (large set):
Got 282923 CrOS Devices...
Traceback (most recent call last):
  File "C:\Users\travis\build\jay0lee\GAM\src\gam.py", line 14989, in <module>
  File "C:\Users\travis\build\jay0lee\GAM\src\gam.py", line 14489, in ProcessGAMCommand
  File "C:\Users\travis\build\jay0lee\GAM\src\gam.py", line 12862, in doPrintCrosDevices
  File "C:\Users\travis\build\jay0lee\GAM\src\gam.py", line 11501, in writeCSVfile
  File "C:\Python38\lib\csv.py", line 157, in writerows
  File "C:\Python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u202e' in position 84: character maps to <undefined>
[23056] Failed to execute script gam

Full steps to reproduce the issue:
gam print cros fields autoupdateexpiration,lastsync,serialnumber,orgunitpath,model,status,annotatedassetid,osversion > c:\devices.csv

The script gets all ChromeOS devices, but fails to output at the end with the error listed above.

**Comment by tmulroy1** [comment]
Rolled back from 4.96 -> 4.95 as another thread suggested. Stills throws the same error, but the output changed to exclude the strange "travis" paths listed above.

Got 282923 CrOS Devices...
Traceback (most recent call last):
  File "gam.py", line 14944, in <module>
  File "gam.py", line 14448, in ProcessGAMCommand
  File "gam.py", line 12830, in doPrintCrosDevices
  File "gam.py", line 11469, in writeCSVfile
  File "csv.py", line 158, in writerows
  File "C:\Python37\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u202e' in position 84: character maps to <undefined>
[17924] Failed to execute script gam

Thanks!

**Comment by dbarcot** [comment]
should it be that python library struggles with "non english" characters (even though Unicode is processed)? Today I struggled with similar issue when trying to set OoO message with accented chars. Once accents removed from OoO message all went well. I was using latest version 4.96 as well
