### ISSUE TITLE
Error when deleting users via csv

### ISSUE THREAD

**Issue by sopwath** [jay0lee/GAM#109]
At the end of a mass delete command, run within PowerShell:
".\gam csv usersToDelete.csv gam delete user ~primaryEmail"

I got the following error at the end of the batch. It looks like the second-to-last user was not deleted, but the other 53 were removed correctly.

Traceback (most recent call last):
  File "<string>", line 8319, in <module>
  File "<string>", line 6476, in doDeleteUser
  File "<string>", line 379, in callGAPI
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.util", line 137, in positional_wrapper
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\googleapiclient.http", line 722, in execute
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.util", line 137, in positional_wrapper
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.client", line 551, in new_request
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\httplib2", line 1608, in request
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\httplib2", line 1350, in _request
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\httplib2", line 1306, in _conn_request
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\httplib", line 1119, in getresponse
httplib.ResponseNotReady

**Comment by jay0lee** [comment]
This is usually a firewall or antivirus software on the machine mucking with GAM's request. Later versions of GAM may handle this error better, be sure you're running the latest release.

Jay
