### ISSUE TITLE
encoding issue when importing email

### ISSUE THREAD

**Issue by L422Y** [jay0lee/GAM#1145]
While importing a bunch of emails exported using the Gmail API, I'm getting an encoding error:
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 61: ordinal not in range(128):

`Traceback (most recent call last):
  File "gam.py", line 11594, in <module>
  File "gam.py", line 11537, in ProcessGAMCommand
  File "gam.py", line 3952, in sendOrDropEmail
  File "gam.py", line 8775, in send_email
  File "email/message.py", line 178, in as_bytes
  File "email/generator.py", line 116, in flatten
  File "email/generator.py", line 181, in _write
  File "email/generator.py", line 214, in _dispatch
  File "email/generator.py", line 272, in _handle_multipart
  File "email/generator.py", line 116, in flatten
  File "email/generator.py", line 181, in _write
  File "email/generator.py", line 214, in _dispatch
  File "email/generator.py", line 432, in _handle_text
  File "email/generator.py", line 249, in _handle_text
  File "email/generator.py", line 155, in _write_lines
  File "email/generator.py", line 406, in write
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 61: ordinal not in range(128)

`

I feel like this is fairly common and just needs a workaround, let me know if otherwise! 

Email in question (sanitized)

[sanitized.eml.zip](https://github.com/jay0lee/GAM/files/4414026/sanitized.eml.zip)

**Comment by jay0lee** [comment]
The issue here is that RFC compliant email data should be 100% ASCII text. Any non-ASCII characters should be encoded to ASCII.

Your sample email uses a non-ASCII single quote in the word Bloomingdale's. I've added code to convert any non-ASCII characters in the message but it may not display perfectly depending on where the unicode characters are in the message.

For now, you can also try converting the file to ASCII with a Linux command:

```
cat sanitized.eml | iconv -f utf-8 -t ascii//TRANSLIT > san-ascii.eml
```

**Comment by jay0lee** [comment]
closing this as fix for these messages will be in next release.
