### ISSUE TITLE
[10744] Failed to execute script __main__

### ISSUE THREAD

**Issue by branyang1** [jay0lee/GAM#1174]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1.C:\Windows\system32>gam user user@ourdomain.com check serviceaccount
2. gam info user
3.

Expected outcome (what are you trying to do?):
Running GAM for the First Time

Actual outcome (what errors or bad behavior do you see instead?):
1. 
Traceback (most recent call last):
  File "gam\__main__.py", line 47, in <module>
  File "gam\__main__.py", line 43, in main
  File "gam\__init__.py", line 11278, in ProcessGAMCommand
  File "gam\__init__.py", line 9803, in getUsersToModify
  File "gam\__init__.py", line 753, in buildGAPIObject
  File "gam\__init__.py", line 697, in getValidOauth2TxtCredentials
  File "gam\auth\oauth.py", line 460, in refresh
  File "gam\auth\oauth.py", line 468, in _locked_refresh
  File "site-packages\google\oauth2\credentials.py", line 177, in refresh
  File "site-packages\google\oauth2\_client.py", line 248, in refresh_grant
  File "site-packages\google\oauth2\_client.py", line 124, in _token_endpoint_request
  File "site-packages\google\oauth2\_client.py", line 60, in _handle_error_response
google.auth.exceptions.RefreshError: ('invalid_grant: reauth related error (invalid_rapt)', '{\n  "error": "invalid_grant",\n  "error_description": "reauth related error (invalid_rapt)",\n  "error_subtype": "invalid_rapt"\n}')
[10744] Failed to execute script __main__

2. Traceback (most recent call last):
  File "gam\__main__.py", line 47, in <module>
  File "gam\__main__.py", line 43, in main
  File "gam\__init__.py", line 10963, in ProcessGAMCommand
  File "gam\__init__.py", line 7825, in doGetUserInfo
  File "gam\__init__.py", line 753, in buildGAPIObject
  File "gam\__init__.py", line 697, in getValidOauth2TxtCredentials
  File "gam\auth\oauth.py", line 460, in refresh
  File "gam\auth\oauth.py", line 468, in _locked_refresh
  File "site-packages\google\oauth2\credentials.py", line 177, in refresh
  File "site-packages\google\oauth2\_client.py", line 248, in refresh_grant
  File "site-packages\google\oauth2\_client.py", line 124, in _token_endpoint_request
  File "site-packages\google\oauth2\_client.py", line 60, in _handle_error_response
google.auth.exceptions.RefreshError: ('invalid_grant: reauth related error (invalid_rapt)', '{\n  "error": "invalid_grant",\n  "error_description": "reauth related error (invalid_rapt)",\n  "error_subtype": "invalid_rapt"\n}')
[10112] Failed to execute script __main__

**Comment by jay0lee** [comment]
will keep this open as GAM could certainly do a better job of catching the error and telling the admin what to do...

**Comment by jay0lee** [comment]
I believe @taers232c fixed this with https://github.com/jay0lee/GAM/commit/0268858784bd23d5ee6c7839e8c687d611f20301

closing for now.

**Comment by Stoppels** [comment]
Still getting this on GAM 5.11 on macOS with little hint as to what to do (`gam oauth create`).

**Comment by jay0lee** [comment]
@Stoppels can you post the exact error you are getting?

**Comment by Stoppels** [comment]
> ➜  ~ gam user x delegate to y
> Traceback (most recent call last):
>   File "gam/__main__.py", line 50, in <module>
>   File "gam/__main__.py", line 45, in main
>   File "gam/__init__.py", line 13789, in ProcessGAMCommand
>   File "gam/__init__.py", line 12136, in getUsersToModify
>   File "gam/__init__.py", line 915, in buildGAPIObject
>   File "gam/__init__.py", line 846, in getValidOauth2TxtCredentials
>   File "gam/auth/oauth.py", line 467, in refresh
>   File "gam/auth/oauth.py", line 475, in _locked_refresh
>   File "site-packages/google/oauth2/credentials.py", line 204, in refresh
>   File "site-packages/google/oauth2/_client.py", line 248, in refresh_grant
>   File "site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
>   File "site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
> google.auth.exceptions.RefreshError: ('invalid_grant: reauth related error (invalid_rapt)', '{\n  "error": "invalid_grant",\n  "error_description": "reauth related error (invalid_rapt)",\n  "error_subtype": "invalid_rapt"\n}')
> [20029] Failed to execute script __main__

`gam oauth create` fixed it now. If I remember correctly, I have to go through `gam oauth create` every time I want to use gam. Is this a setup error on my part?
I don't recall getting this vague error before though, this Github issue was the only search result for that last line.

**Comment by Stoppels** [comment]
For the record, I'm not sure where things have gone wrong, but even after reinstalling or wiping the credentials files I've had to do this every time.

**Comment by jay0lee** [comment]
See:

https://workspaceupdates.googleblog.com/2020/11/session-length-cloud-console-update-exempt-apps.html

GAM uses Google Cloud storage API to download Google Vault exports so it is
subject to the GCP session length you've configured in your admin console.

You can:

1) Reauthorize GAM without Google Cloud Storage API so that it's no longer
subject to the session length.

2) Add GAM to the allowlist per above blog.

3) deal with constant reauth as you're doing now.

Jay
