### ISSUE TITLE
Cannot show calendars of user

### ISSUE THREAD

**Issue by killebrewj** [jay0lee/GAM#129]
When I run gam user whoever@domain.com show calendars, I get this with various recent versions of gam. Any ideas?

Traceback (most recent call last):
  File "<string>", line 7599, in <module>
  File "<string>", line 1578, in showCalendars
  File "<string>", line 623, in buildGAPIServiceObject
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.util", line 137, in positional_wrapper
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\googleapiclient.discovery", line 196, in build
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.util", line 137, in positional_wrapper
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.client", line 534, in new_request
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.client", line 748, in _refresh
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.client", line 772, in _do_refresh_request
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.client", line 1379, in _generate_refresh_request
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.client", line 1508, in _generate_assertion
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.crypt", line 271, in from_string
NotImplementedError: PKCS12 format is not supported by the PyCrypto library. Try converting to a "PEM" (openssl pkcs12 -in xxxxx
 is an option.

**Comment by jay0lee** [comment]
You need to walk through the service account setup instructions at:

https://github.com/jay0lee/GAM/wiki/CreatingClientSecretsFile

if you still have trouble, please post to the discussion group (this area is for bugs):

https://groups.google.com/forum/#!forum/google-apps-manager
