### ISSUE TITLE
GAM 5.24 getting error when running certain commands 

### ISSUE THREAD

**Issue by sinclair427** [jay0lee/GAM#1310]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue. Yes I have upgraded 
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki: Yes typing the commands in the GAM wiki as described 

Full steps to reproduce the issue:
1.
2.
3.

Expected outcome (what are you trying to do?):
When running a command to delete or add delegates to a mailbox getting following error message: Traceback (most recent call last):
  File "gam/__main__.py", line 50, in <module>
  File "gam/__main__.py", line 45, in main
  File "gam/__init__.py", line 11556, in ProcessGAMCommand
  File "gam/__init__.py", line 1470, in deleteDelegate
  File "gam/__init__.py", line 1109, in buildGmailGAPIObject
  File "gam/__init__.py", line 1068, in buildGAPIServiceObject
  File "google/oauth2/service_account.py", line 361, in refresh
  File "google/oauth2/_client.py", line 153, in jwt_grant
  File "google/oauth2/_client.py", line 105, in _token_endpoint_request
  File "gam/transport.py", line 80, in wrapped_request_method
  File "gam/transport.py", line 93, in __call__
  File "google_auth_httplib2.py", line 116, in __call__
  File "httplib2/__init__.py", line 1985, in request
  File "httplib2/__init__.py", line 1650, in _request
  File "httplib2/__init__.py", line 1621, in _conn_request
  File "httplib2/__init__.py", line 460, in _decompressContent
  File "gzip.py", line 300, in read
  File "gzip.py", line 506, in read
EOFError: Compressed file ended before the end-of-stream marker was reached
[3423] Failed to execute script __main__Actual outcome (what errors or bad behavior do you see instead?):

**Comment by jay0lee** [comment]
The first step is to upgrade to the latest version and see if that fixes the issue. https://git.io/gam-releases.
