### ISSUE TITLE
Installed GAM 6.05 over the top of GAM 4.99 and I can not get gam user info to run.  Anytime I run a command I get:

### ISSUE THREAD

**Issue by Kfry-smbsd** [jay0lee/GAM#1391]
If you need help with GAM, please do not file an issue here, it will be closed and ignored.

Please post your question to the GAM discussion group where other admins are ready and willing to help:

https://groups.google.com/g/google-apps-manager

**Comment by Kfry-smbsd** [comment]
Traceback (most recent call last):
  File "gam\__main__.py", line 50, in <module>
  File "gam\__main__.py", line 45, in main
  File "gam\__init__.py", line 11455, in ProcessGAMCommand
  File "gam\__init__.py", line 8764, in doGetUserInfo
  File "gam\__init__.py", line 997, in buildGAPIObject
  File "gam\__init__.py", line 925, in getValidOauth2TxtCredentials
  File "gam\auth\oauth.py", line 467, in refresh
  File "gam\auth\oauth.py", line 475, in _locked_refresh
  File "google\oauth2\credentials.py", line 228, in refresh
  File "google\oauth2\reauth.py", line 338, in refresh_grant
  File "google\oauth2\_client.py", line 60, in _handle_error_response
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
[11352] Failed to execute script __main__

**Comment by jay0lee** [comment]
Try deleting oauth2.txt in the same folder as GAM and then re-authenticating.

**Comment by Kfry-smbsd** [comment]
That looks like it did the trick.  Thank you.
