### ISSUE TITLE
GAM setup fails under Python 2.6.6

### ISSUE THREAD

**Issue by daparker** [jay0lee/GAM#1415]
I am trying to install the legacy version of GAM 6.07 on Linux with glibc 2.11.3 and Python 2.6.6.  When I run `gam create project` the creation and setup of the project works successfully and after all of the steps, I eventually get this:

`That's it! Your GAM Project is created and ready to use.`

But when I subsequently run a command like `gam info domain` it goes through the setup of scopes again, and errors out after the verification step.  A sanitized version of the output is pasted below under **Actual outcome**.

Full steps to reproduce the issue:
1. Download and extract gam-6.07-linux-x86_64-legacy.tar.xz on a Linux system with Python 2.6.6.
2. Run `gam create project` and go through all of the steps.
3. Run `gam info domain` and go through the steps.

Expected outcome (what are you trying to do?):
GAM should run through the first-time setup of the scopes, and then work normally.

Actual outcome (what errors or bad behavior do you see instead?):
GAM crashes:

```
Go to the following link in your browser:

	https://gam-shortn.appspot.com/XXXXXXXX

Enter verification code: XXXXXXXXXXXX
Traceback (most recent call last):
  File "gam/__main__.py", line 50, in <module>
  File "gam/__main__.py", line 45, in main
  File "gam/__init__.py", line 11485, in ProcessGAMCommand
  File "gam/gapi/directory/domains.py", line 25, in info
  File "gam/gapi/directory/customer.py", line 18, in doGetCustomerInfo
  File "gam/gapi/directory/__init__.py", line 5, in build
  File "gam/__init__.py", line 1024, in buildGAPIObject
  File "gam/__init__.py", line 8743, in _getValueFromOAuth
  File "gam/auth/oauth.py", line 413, in get_token_value
  File "gam/auth/oauth.py", line 397, in _fetch_id_token_data
  File "google/oauth2/id_token.py", line 146, in verify_oauth2_token
  File "google/oauth2/id_token.py", line 126, in verify_token
  File "google/auth/jwt.py", line 278, in decode
  File "google/auth/jwt.py", line 198, in _verify_iat_and_exp
ValueError: Token used too early, 1629749858 < 1629749909
[14883] Failed to execute script __main__
```

**Comment by daparker** [comment]
It looks like ntpd was not running on this server and the time was about 30 seconds behind.  I have corrected that and will test again.

**Comment by daparker** [comment]
Confirmed that this was due to the time offset and not a Python version issue.  Sorry!
