### ISSUE TITLE
GAM 6.09 Crashing on "gam print cros allfields"

### ISSUE THREAD

**Issue by emf2718** [jay0lee/GAM#1437]
Just updated to 6.09.  On a run of "gam print cros allfields", received this after all devices were fetched:
`Traceback (most recent call last):
  File "gam\__main__.py", line 50, in <module>
  File "gam\__main__.py", line 45, in main
  File "gam\__init__.py", line 11652, in ProcessGAMCommand
  File "gam\gapi\directory\cros.py", line 871, in doPrintCrosDevices
  File "gam\display.py", line 246, in write_csv_file
  File "csv.py", line 157, in writerows
_csv.Error: need to escape, but no escapechar set
[17240] Failed to execute script '__main__' due to unhandled exception!`

Previous versions of GAM were fine.

**Comment by jay0lee** [comment]
I suspect this has something to do with the upgrade to Python 3.10.0. I
can't reproduce the error though. What OS are you using?

Jay Lee

**Comment by emf2718** [comment]
Windows 10.  Could it be the number of devices?  We have over 65,000.  Are there any other things I could send that might help?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jay0lee** [comment]
No, thanks. I figured out how to reproduce the error in my environment so
now just need to confirm the fix.

**Comment by jay0lee** [comment]
BTW, I'd really recommend against using allfields unless you REALLY need
all fields. It's much more efficient to just list the actual fields you
use. You get better performance and it'll likely work around this bug
