### ISSUE TITLE
GAM 6.12 - cryptography error on macOS arm64

### ISSUE THREAD

**Issue by zk-1** [jay0lee/GAM#1465]
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

**Please confirm the following:**
[x] I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
[x] I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

**Full steps to reproduce the issue:**
1. Fresh install of, or upgrade to GAM **6.12** on Apple M1 computer (arm64) [running macOS 12.1] using recommended method
2. Try to create new project, or rotate service account keys using `gam rotate sakey` 

**Expected outcome (what are you trying to do?):**
GAM executes command without error. Specifically, it succeeds in generating a new private key as part of the process.

**Actual outcome (what errors or bad behavior do you see instead?):**
Command fails with error:
```
Generating new private key...
Traceback (most recent call last):
  File "gam/__main__.py", line 50, in <module>
  File "gam/__main__.py", line 45, in main
  File "gam/__init__.py", line 11905, in ProcessGAMCommand
  File "gam/__init__.py", line 7945, in doCreateOrRotateServiceAccountKeys
  File "gam/__init__.py", line 7770, in _generatePrivateKeyAndPublicCert
  File "cryptography/hazmat/backends/__init__.py", line 14, in default_backend
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cryptography/hazmat/backends/openssl/backend.py", line 113, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
ImportError: dlopen(/var/folders/35/5hfq7vfx5_nbx34xrmz_9pyr0000gn/T/_MEIspB51F/cryptography/hazmat/bindings/_openssl.abi3.so, 0x0002): tried: '/var/folders/35/5hfq7vfx5_nbx34xrmz_9pyr0000gn/T/_MEIspB51F/cryptography/hazmat/bindings/_openssl.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_openssl.abi3.so' (no such file), '/usr/lib/_openssl.abi3.so' (no such file), '/private/var/folders/35/5hfq7vfx5_nbx34xrmz_9pyr0000gn/T/_MEIspB51F/cryptography/hazmat/bindings/_openssl.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_openssl.abi3.so' (no such file), '/usr/lib/_openssl.abi3.so' (no such file)
[23869] Failed to execute script '__main__' due to unhandled exception!
```

**Workaround:**
GAM 6.11 still works fine, and downgrading to v6.11 using `bash <(curl -s -S -L https://git.io/install-gam) -l -v 6.11` works as a temporary workaround.
I'm assuming this bug is something to do with the change '_ARM and ARM64 binaries reintroduced._' in v6.12.

Thanks Jay, Ross & co for your great work!

**Comment by duffyke** [comment]
Just wanted to confirm this bug is happening to me as well.

Thank you all for your hard work.

**Comment by pew10** [comment]
I'm seeing this on Apple silicon. The install runs fine on an older Intel Mac. (Both systems are running macOS 12.1)

**Comment by jay0lee** [comment]
The biggest challenge in troubleshooting this one is I don't have an Apple M1 device to reproduce this with and can't really justify the expense right now. If anyone cares though I'm happy to setup some sort of go fund me or I can take PayPal and Venmo.

**Comment by pew10** [comment]
Jay, A go fund me might not be a bad idea. The M1 MBA is very high value. Fully loaded with AppleCare getting 100 people to donate $20 each would cover it. Easier said than done I suppose. 

I did get GAM going on on older intel system I have. Thanks for all of your work on this. - pew

**Comment by zk-1** [comment]
@jay0lee, I and no doubt many others would be glad to chip in to an M1 fund if you feel it's important for the ongoing development of GAM for Mac. An M1 Mac mini could be another economical route to having an M1 system for testing.

In the meantime, I can offer to set you up an SSH connection to a blank-install network-isolated M1 Mac for a block of hours in the next week or two for debugging purposes, if you'd like. Let me know if interested and I can email you to arrange it, if not no worries.

**Comment by jay0lee** [comment]
Can someone with an M1 test the build below and see if it has the same issues
[gam-macos-m1-fixed-take1.zip](https://github.com/jay0lee/GAM/files/7840996/gam-macos-m1-fixed-take1.zip)
?

**Comment by taers232c** [comment]
The executable fails, running from source works.
 ./gam rotate sakey
 Generating new private key...
Traceback (most recent call last):
  File "gam/__main__.py", line 50, in <module>
  File "gam/__main__.py", line 45, in main
  File "gam/__init__.py", line 11907, in ProcessGAMCommand
  File "gam/__init__.py", line 7945, in doCreateOrRotateServiceAccountKeys
  File "gam/__init__.py", line 7770, in _generatePrivateKeyAndPublicCert
  File "cryptography/hazmat/backends/__init__.py", line 14, in default_backend
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cryptography/hazmat/backends/openssl/backend.py", line 113, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
ImportError: dlopen(/var/folders/n4/gdj8f3dj2mqckqxdnvxq9q480000gp/T/_MEI1YyxtW/cryptography/hazmat/bindings/_openssl.abi3.so, 0x0002): tried: '/var/folders/n4/gdj8f3dj2mqckqxdnvxq9q480000gp/T/_MEI1YyxtW/cryptography/hazmat/bindings/_openssl.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_openssl.abi3.so' (no such file), '/usr/lib/_openssl.abi3.so' (no such file), '/private/var/folders/n4/gdj8f3dj2mqckqxdnvxq9q480000gp/T/_MEI1YyxtW/cryptography/hazmat/bindings/_openssl.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_openssl.abi3.so' (no such file), '/usr/lib/_openssl.abi3.so' (no such file)
[93655] Failed to execute script '__main__' due to unhandled exception!

**Comment by jay0lee** [comment]
What does

gam version extended

Show for these devices?

Jay

**Comment by taers232c** [comment]
$ ./gam.py version extended
GAM 6.12 - https://git.io/gam - pythonsource
Jay Lee <jay0lee@gmail.com>
Python 3.10.1 64-bit final
google-api-python-client 2.33.0
MacOS Monterey 12.0.1 arm64
Path: /Users/ross/Downloads/GAM-main/src
Your system time differs from admin.googleapis.com by less than 1 second
OpenSSL 1.1.1l  24 Aug 2021
cryptography 36.0.0
filelock 3.4.0
google-auth-httplib2 0.1.0
google-auth-oauthlib 0.4.6
google-auth 2.3.3
httplib2 0.20.2
passlib 1.7.4
python-dateutil 2.8.2
admin.googleapis.com (142.251.32.234) connects using TLSv1.3 TLS_AES_256_GCM_SHA384

**Comment by jay0lee** [comment]
That's sort of surprising, at one point it was always showing x86_64 even
on M1s. So it looks like PyInstaller and python are running as arm64 but
cryptography module included is x86_64 only. Hmmm....

Jay

**Comment by jay0lee** [comment]
OK, another day another build. Can someone test this one on a M1 and report back here?

[gam-mac-m1-fix-take2.zip](https://github.com/jay0lee/GAM/files/7847539/gam-mac-m1-fix-take2.zip)

**Comment by taers232c** [comment]
$ ./gam version 
Traceback (most recent call last):
  File "gam/__main__.py", line 29, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "gam/__init__.py", line 47, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cryptography/x509/__init__.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cryptography/x509/certificate_transparency.py", line 10, in <module>
ImportError: dlopen(/var/folders/n4/gdj8f3dj2mqckqxdnvxq9q480000gp/T/_MEIU9WfVr/cryptography/hazmat/bindings/_rust.abi3.so, 0x0002): tried: '/var/folders/n4/gdj8f3dj2mqckqxdnvxq9q480000gp/T/_MEIU9WfVr/cryptography/hazmat/bindings/_rust.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_rust.abi3.so' (no such file), '/usr/lib/_rust.abi3.so' (no such file), '/private/var/folders/n4/gdj8f3dj2mqckqxdnvxq9q480000gp/T/_MEIU9WfVr/cryptography/hazmat/bindings/_rust.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_rust.abi3.so' (no such file), '/usr/lib/_rust.abi3.so' (no such file)
[4130] Failed to execute script '__main__' due to unhandled exception!

**Comment by jay0lee** [comment]
Once more for the day. Can someone test the below and let me know?
[gam-m1-fix-3s-a-charm.zip](https://github.com/jay0lee/GAM/files/7849778/gam-m1-fix-3s-a-charm.zip)

**Comment by taers232c** [comment]
3s-a-charm

$ ./gam version check
Traceback (most recent call last):
  File "gam/__main__.py", line 28, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "gam/__init__.py", line 47, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cryptography/x509/__init__.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cryptography/x509/certificate_transparency.py", line 10, in <module>
ImportError: dlopen(/var/folders/n4/gdj8f3dj2mqckqxdnvxq9q480000gp/T/_MEI0QUiju/cryptography/hazmat/bindings/_rust.abi3.so, 0x0002): tried: '/var/folders/n4/gdj8f3dj2mqckqxdnvxq9q480000gp/T/_MEI0QUiju/cryptography/hazmat/bindings/_rust.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_rust.abi3.so' (no such file), '/usr/lib/_rust.abi3.so' (no such file), '/private/var/folders/n4/gdj8f3dj2mqckqxdnvxq9q480000gp/T/_MEI0QUiju/cryptography/hazmat/bindings/_rust.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_rust.abi3.so' (no such file), '/usr/lib/_rust.abi3.so' (no such file)
[4986] Failed to execute script '__main__' due to unhandled exception!

**Comment by jay0lee** [comment]
OK, I've turned off universal2 for now and GAM on MacOS M1 should just use x86_64 emulation. GAM 6.13 is out with this fix.

**Comment by taers232c** [comment]
I've verified, thanks

Ross
--
***@***.***
