### ISSUE TITLE
user <user> show filelist breaks on upgrade to 3.6.5

### ISSUE THREAD

**Issue by simpsonjulian** [jay0lee/GAM#230]
I'm running the latest GAM, using the command as describe in the wiki, and we pay for our Google Apps.

Part of our offboarding script runs `gam user $user show filelist id`.

Full steps to reproduce the issue:
1. Run that command against GAM 3.6.3 with my creds. It works.
2.Run that cpmmand against GAM 3.6.5 with my creds
3. Observe Python Traceback:

    Traceback (most recent call last):
     File "../../gam/src/gam.py", line 9523, in <module>
    showDriveFiles(users)
    File "../../gam/src/gam.py", line 3414, in showDriveFiles
    drive = buildGAPIServiceObject(u'drive', user)
    File "../../gam/src/gam.py", line 853, in buildGAPIServiceObject
    json_data, scopes)
    File "<PARENT DIR>/GAM-3.65/src/oauth2client/service_account.py", line 216, in from_json_keyfile_dict
    return cls._from_parsed_json_keyfile(keyfile_dict, scopes)
    File "<PARENT DIR>/GAM-3.65/src/oauth2client/service_account.py", line 161, in _from_parsed_json_keyfile
    'Expected', SERVICE_ACCOUNT)````

Expected outcome (what are you trying to do?):
Get a list of files for a user

Actual outcome (what errors or bad behavior do you see instead?):
Exit with Traceback

**Comment by tonyhall71** [comment]
I get the same sort of error when running 

gam user $user show filelist todrive

---Error---
Traceback (most recent call last):
  File "<string>", line 9523, in <module>
  File "<string>", line 3414, in showDriveFiles
  File "<string>", line 869, in buildGAPIServiceObject
NameError: global name 'scope' is not defined

**Comment by jay0lee** [comment]
Closing as I believe this is fixed in latest release. Feel free to re-open if this can still be reproduced.
