### ISSUE TITLE
Unable to run `gam info org` command

### ISSUE THREAD

**Issue by deinspanjer** [jay0lee/GAM#239]
The issue tracker is for reporting product deficiencies. How do I questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:

- [x] I have upgraded to the latest GAM release from http://git.io/gamreleases and I still have this issue.
- [X] I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/GAM/wiki
- [X] I am using a Google Apps for Work, Unlimited or EDU account (Google Apps Standard / Free is not supported)

Full steps to reproduce the issue:
1. `gam info org employees`

Expected outcome (what are you trying to do?):
See information about the org in my gfw account called employees

Actual outcome (what errors or bad behavior do you see instead?):
den:gam dre$ gam info org employees
```
Traceback (most recent call last):
  File "/Users/dre/gam/gam.py", line 33, in <module>
    import httplib2
  File "/Users/dre/gam/httplib2/__init__.py", line 34, in <module>
    import gzip
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 10, in <module>
    import io
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```

**Comment by deinspanjer** [comment]
I'm sorry, it appears something just broke in my Python install while I was in the middle of running different gam commands.  I'll sort it out.
