### ISSUE TITLE
GAM 3.72 64-bit for Windows not working here

### ISSUE THREAD

**Issue by regexaurus** [jay0lee/GAM#293]
I downloaded and extracted gam-3.7-windows-x64.zip and generated/saved client_secrets.json and oauth2service.json in the same directory where gam.exe was extracted. Any gam.exe command (e.g. _gam.exe oauth info_) I try (using Windows command prompt, with the directory where gam.exe resides as the current working directory) shows an authorized scope selection menu, with each item selected except 7) and 16). If I type _s_ to select all scopes then type _c_ to continue to authorization, it just goes back to showing the scope selection menu. If I type _e_ to exit without changes, I see errors like this:

> Traceback (most recent call last):
>   File "gam.py", line 11249, in <module>
>   File "gam.py", line 10853, in ProcessGAMCommand
>   File "gam.py", line 10213, in OAuthInfo
> AttributeError: 'NoneType' object has no attribute 'user_agent'
> Failed to execute script gam

Probably missed something...any ideas?

Thank you!

**Comment by regexaurus** [comment]
Sorry, this apparently was my problem.
Typing _c_ (Continue to authorization) immediately instead of first selecting all entries worked.
