### ISSUE TITLE
ERROR: cannot instantiate ctype 'EVP_MD_CTX' of unknown size after upgrade to Fedora 25

### ISSUE THREAD

**Issue by tiemen** [jay0lee/GAM#350]
Latest version of GAM (installed with the command in the Readme).

Full steps to reproduce the issue:
1. upgrade to Fedora 25
2.  run any gam command
3. produces ERROR: cannot instantiate ctype 'EVP_MD_CTX' of unknown size

Full traceback:

Traceback (most recent call last):
  File "/home/t.ruiten@ad.rdmedia.com/bin/GAM/RD/gam.py", line 9620, in <module>
    doDelegates(users)
  File "/home/t.ruiten@ad.rdmedia.com/bin/GAM/RD/gam.py", line 1129, in doDelegates
    emailsettings = getEmailSettingsObject()
  File "/home/t.ruiten@ad.rdmedia.com/bin/GAM/RD/gam.py", line 930, in getEmailSettingsObject
    return initGDataObject(gdata.apps.emailsettings.service.EmailSettingsService(), u'email-settings')
  File "/home/t.ruiten@ad.rdmedia.com/bin/GAM/RD/gam.py", line 911, in initGDataObject
    getGDataOAuthToken(gdataObj)
  File "/home/t.ruiten@ad.rdmedia.com/bin/GAM/RD/gam.py", line 625, in getGDataOAuthToken
    credentials.refresh(http)
  File "/home/t.ruiten@ad.rdmedia.com/bin/GAM/RD/oauth2client/client.py", line 626, in refresh
    self._refresh(http.request)
  File "/home/t.ruiten@ad.rdmedia.com/bin/GAM/RD/oauth2client/client.py", line 835, in _refresh
    self._do_refresh_request(http_request)
  File "/home/t.ruiten@ad.rdmedia.com/bin/GAM/RD/oauth2client/client.py", line 862, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/home/t.ruiten@ad.rdmedia.com/bin/GAM/RD/oauth2client/client.py", line 1541, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/home/t.ruiten@ad.rdmedia.com/bin/GAM/RD/oauth2client/client.py", line 1670, in _generate_assertion
    private_key, self.private_key_password), payload)
  File "/home/t.ruiten@ad.rdmedia.com/bin/GAM/RD/oauth2client/crypt.py", line 92, in make_signed_jwt
    signature = signer.sign(signing_input)
  File "/home/t.ruiten@ad.rdmedia.com/bin/GAM/RD/oauth2client/_openssl_crypt.py", line 99, in sign
    return crypto.sign(self._key, message, 'sha256')
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 2563, in sign
    md_ctx = _ffi.new("EVP_MD_CTX*")
TypeError: cannot instantiate ctype 'EVP_MD_CTX' of unknown size

I found this report for oauth2client: https://github.com/google/oauth2client/issues/641

Not sure if this is an issue in Fedora or GAM, rpm versions:

python2-cryptography: 1.5.3-3.fc25
python3-cryptography: 1.5.3-3.fc25
pyOpenSSL: 16.0.0-2.fc25

**Comment by tiemen** [comment]
Never mind, this is an issue in Fedora. Downgrade to python2-cryptography-1.3.1-4.fc25 resolved the issue for now. Probably need to wait for pyOpenSSL-16.1.0 to land in Fedora:

https://pyopenssl.readthedocs.io/en/stable/changelog.html
