### ISSUE TITLE
UnicodeEncodeError / show calendars

### ISSUE THREAD

**Issue by lordhadespl** [jay0lee/GAM#47]
CMD: gam user <user> show calendars

Traceback (most recent call last):
  File "gam.py", line 7591, in <module>
  File "gam.py", line 1574, in showCalendars
  File "encodings\cp852.pyo", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode character u'\xf5' in position 2
1: character maps to <undefined>

**Comment by jay0lee** [comment]
gam user show calendars is not a valid command. Please report your problem to the mailing list before filing a bug.

**Comment by lordhadespl** [comment]
There is a bug, I only didn't write specific user in this request, but of course in my CMD it is.
gam user mysuser@domain.com show calendars.

It gives:
Traceback (most recent call last):
  File "gam.py", line 7591, in <module>
  File "gam.py", line 1574, in showCalendars
  File "encodings\cp852.pyo", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode character u'\xf5' in position 2
1: character maps to <undefined>

--------
on above "gam user show calendars" surely it gives proper msg:
Error: calendars is not a valid gam command
