### ISSUE TITLE
Issue installing GAM

### ISSUE THREAD

**Issue by gmahler** [jay0lee/GAM#477]
Traceback (most recent call last):
  File "gam.py", line 11190, in <module>
  File "gam.py", line 10426, in ProcessGAMCommand
  File "gam.py", line 399, in SetGlobalVariables
  File "gam.py", line 436, in doGAMCheckForUpdates
  File "httplib2\__init__.py", line 1659, in request
  File "httplib2\__init__.py", line 1399, in _request
  File "httplib2\__init__.py", line 1355, in _conn_request
  File "httplib.py", line 1123, in getresponse
httplib.ResponseNotReady
Failed to execute script gam

I keep getting this for any command I type.

**Comment by jay0lee** [comment]
This error is usually caused by a firewall or antivirus / security software on your computer or network. try disabling them and rerunning.

**Comment by jcummings** [comment]
I get the same error on a Windows 2012 R2 system.  Doesn't matter if the firewall is on/off, nor is the error affected by turning off SEP.  It looks like there's some dependency that the server doesn't have but there's no installation requirement document that indicates anything is required to install.
