### ISSUE TITLE
GAM issue with returned result with Unicode characters

### ISSUE THREAD

**Issue by jadethaveekij** [jay0lee/GAM#490]
Running latest gam 4.21 version on Windows x64 

C:\gam>gam info group mygroupname

<many information sniffed> 
Traceback (most recent call last):
  File "gam.py", line 11190, in <module>
  File "gam.py", line 10572, in ProcessGAMCommand
  File "gam.py", line 7948, in doGetGroupInfo
  File "encodings\cp874.py", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode character u'\xe9' in position 152: character maps to <undefined>
Failed to execute script gam

There was a problem when a username contains special Accents characters.  This seemed to be universal to several commands (show delegate, show group members, etc).

**Comment by taers232c** [comment]
Code page 874 is the Thai code page, u'\xe9' is an e with an acute accent which does not appear on that code page, thus the error.
If you're not using Thai characters, try changing the code page to 1252, the command is: chcp 1252

Ross
--
ross.scroggs@gmail.com

**Comment by jadethaveekij** [comment]
Does this refers to the fact that if my Windows locale is something, and the characters returned from Gam is different, I have to use chcp to change the display language accordingly?  Sorry for being newbie here.

**Comment by taers232c** [comment]
Yes.
--
ross.scroggs@gmail.com
