### ISSUE TITLE
can not authenticate into domains

### ISSUE THREAD

**Issue by stefanosaccone** [jay0lee/GAM#55]
Hi,

using this commands:

gam info domain
press enter
insert 22 to continue

we get this error

Traceback (most recent call last):
  File "gam.py", line 7416, in <module>
  File "gam.py", line 5533, in doGetDomainInfo
  File "gam.py", line 516, in buildGAPIObject
  File "gam.py", line 7267, in doRequestOAuth
  File "oauth2client\util.pyo", line 129, in positional_wrapper
  File "oauth2client\tools.pyo", line 183, in run_flow
  File "oauth2client\util.pyo", line 129, in positional_wrapper
  File "googleapiclient\http.pyo", line 723, in execute
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.goo
gleapis.com/urlshortener/v1/url?alt=json returned "Daily Limit for Unauthenticat
ed Use Exceeded. Continued use requires signup.">

this happens in every device into our company.
This not happens if you have already an .oauth file to get authenticated into a domain.
.json file and all things that we must do on AppEngine console has been made

is it a known issue?
please let me know
regards
Stefano Saccone from Noovle SRL

**Comment by jay0lee** [comment]
Known and fixed in GAM 3.43. Go ahead and upgrade to the latest version and
it should go away:

http://git.io/gamreleases


Jay Lee

**Comment by stefanosaccone** [comment]
Many thanks!

Cordiali Saluti
*Stefano Saccone*
*Google Apps Certified Administrator*
*Technical Support* - Noovle S.r.l.
fisso: +39 055 051 051 3
mail: stefano.saccone@noovle.it
________

Noovle <http://www.noovle.it/> | The Nexus of forces

2015-04-02 17:31 GMT+02:00 Jay Lee <notifications@github.com>:
