### ISSUE TITLE
No crypto library available

### ISSUE THREAD

**Issue by lqkme2** [jay0lee/GAM#59]
Not sure if I need to open a new issue or not since the other was closed https://github.com/jay0lee/GAM/issues/19

```
~ >> gam version
Dito GAM 3.43 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.7.9 64-bit final
google-api-python-client 1.3.1
Darwin-14.3.0-x86_64-i386-64bit x86_64
Path: /Users/###/scratch/gam/
 ~ >> gam user user@domain.com show filelist
Traceback (most recent call last):
  File "/Users/###/scratch/gam/gam.py", line 7605, in <module>
    showDriveFiles(users)
  File "/Users/###/scratch/gam/gam.py", line 1879, in showDriveFiles
    drive = buildGAPIServiceObject(u'drive', user)
  File "/Users/###/scratch/gam/gam.py", line 596, in buildGAPIServiceObject
    credentials = oauth2client.client.SignedJwtAssertionCredentials(SERVICE_ACCOUNT_EMAIL, key, scope=scope, sub=act_as)
  File "/Users/###/scratch/GAM/oauth2client/util.py", line 129, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/###/scratch/GAM/oauth2client/client.py", line 1354, in __init__
    _RequireCryptoOrDie()
  File "/Users/###/scratch/GAM/oauth2client/client.py", line 1308, in _RequireCryptoOrDie
    raise CryptoUnavailableError('No crypto library available')
oauth2client.client.CryptoUnavailableError: No crypto library available
```
 `gam info user` and ` gam info user user@domian.com` works fine for example. I even scraped the `GAM` folder, resynced with GitHub for OS X, recreated client_secrets.json, oauth2service.json and oauth2service.p12, modified "manage API client access", and reaccepted access for the app from Google.

**Comment by calerogers** [comment]
I am also having the same issue. I tried updating to the latest release 3.51 and recreated the json files. Any luck @lqkme2 ?

**Comment by MrRoub** [comment]
Thanks for the help @calerogers ! Installing the pycrypto python module (https://pypi.python.org/pypi/pycrypto/2.6.1) solved it for me as well.
