### ISSUE TITLE
Error reading file list

### ISSUE THREAD

**Issue by jkrauska** [jay0lee/GAM#62]
Reading a file list for one of my users causes an error in 3.43a

 got 65 files for myuser@mydomain.org...
Traceback (most recent call last):
  File "/home/googbackup/gam/gam.py", line 7605, in <module>
    showDriveFiles(users)
  File "/home/googbackup/gam/gam.py", line 1896, in showDriveFiles
    a_file[attrib] = u' '.join(file[attrib])
TypeError: sequence item 0: expected string or Unicode, dict found

Please advise?

**Comment by dwang99** [comment]
used both 3.45 and 3.5 gam.exe 32bit 

having a similar issue when using the allfields switch for a user:

gam.exe user user@domain.com show filelist allfields

getting an error of:

Traceback (most recent call last):
  File "<string>", line 8435, in <module>
  File "<string>", line 2642, in showDriveFiles
TypeError: sequence item 0: expected string or Unicode, dict found

If I don't use allfields it works fine.

**Comment by timwsuqld** [comment]
Same issue, also using allfields, running tag v3.61
```
Traceback (most recent call last):
  File "/home/timw/GAM/gam.py", line 9003, in <module>
    showDriveFiles(users)
  File "/home/timw/GAM/gam.py", line 3088, in showDriveFiles
    a_file[attrib] = u' '.join(f_file[attrib])
TypeError: sequence item 0: expected string or Unicode, dict found
```

**Comment by cmonsma** [comment]
Same issue, it seems like there must be a "special character" issue where a filename chokes GAM.  Does anyone have a list of characters that might be a problem?

Traceback (most recent call last):
  File "<string>", line 9412, in <module>
  File "<string>", line 3446, in showDriveFiles
TypeError: sequence item 0: expected string or Unicode, dict found

**Comment by umeditor** [comment]
Seeing this in GAM-3.65:

```
$ /gam.py user EMAIL show filelist allfields
. . .
Traceback (most recent call last):
  File "./gam.py", line 9523, in <module>
    showDriveFiles(users)
  File "./gam.py", line 3433, in showDriveFiles
    a_file[attrib] = u' '.join(f_file[attrib])
TypeError: sequence item 0: expected string or Unicode, dict found
```
