### ISSUE TITLE
GAM issue with Windows Env Variables

### ISSUE THREAD

**Issue by bondurantdt** [jay0lee/GAM#65]
Hello,

Nothing major, but when I create an environment variable to the folder of gam in Windows (run on Win7 x64 latest patches) using 3.45 GAM x64 I run into an issue where GAM expects the client_secrets.json file wherever my working directory is versus the root of the GAM install.

Example:
CMD prompt open
Working Dir: C:\users\<username>  ; GAM install C:\gam with an env var set to C:\gam
client_secrets.json exists in C:\gam
Run gam info domain from working dir
Get the auth scope workflow instead of domain info.
Change working directory to C:\gam
Run gam info domain again
Works as expected.

**Comment by mmmhoppy** [comment]
I can verify and reproduce this issue in GAM (64 bit versions) 3.44 and 3.45 (Win7 Enterprise, SP1 x64). Was working previous to upgrade from v3.05 on same PC.

	Z:\SOMEDIR>gam
	GAM 3.45 - http://git.io/gam
	...
	...

GAM is in the %PATH% variable as you can see below. And the gam.exe command will run fine as shown above using the same environmental variable...
	
	Z:\SOMEDIR>echo %PATH%
	C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;...;P:\GPG;P:\gam-64

Z:\SOMEDIR does not have a client_secrets.json file; if a real gam command which requires authorization is run from this location I get the following output:

	Z:\SOMEDIR>gam audit export status

	Select the authorized scopes for this token. Include a 'r' to grant read-only
	access or an 'a' to grant action-only access.

	[*]  0)  Group Directory API (supports read-only)
	...
		 20)  Select all scopes
		 21)  Unselect all scopes
		 22)  Continue
	22

	WARNING: Please configure OAuth 2.0

	To make GAM run you will need to populate the client_secrets.json file
	found at:

	   Z:\SOMEDIR\client_secrets.json

	with information from the APIs Console <https://cloud.google.com/console>.

	See:

	https://github.com/jay0lee/GAM/wiki/CreatingClientSecretsFile

	for instructions.

Copied client_secrets.json to :\SOMEDIR; FAIL

	Z:\SOMEDIR>copy p:\gam-64\client_secrets.json .
	        1 file(s) copied.

	Z:\SOMEDIR>gam audit export status
	
	Select the authorized scopes for this token. Include a 'r' to grant read-only
	access or an 'a' to grant action-only access.

	[*]  0)  Group Directory API (supports read-only)
	...
		 20)  Select all scopes
		 21)  Unselect all scopes
		 22)  Continue
	22

At this point I am redirected to a browser window to auth with Google.... Enter credentials --> GAM would like to: --> The authentication flow has completed. Then FAIL

	Your browser has been opened to visit:

	...

	If your browser is on a different machine then exit and re-run this
	after creating a file called nobrowser.txt in the same path as GAM.

	Traceback (most recent call last):
	  File "<string>", line 7498, in <module>
	  File "<string>", line 6764, in doStatusExportRequests
	  File "<string>", line 682, in getAuditObject
	  File "<string>", line 323, in tryOAuth
	  File "<string>", line 7277, in doRequestOAuth
	  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.util", line 137, in positional_wrapper
	  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.tools", line 233, in run_flow
	  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.util", line 137, in positional_wrapper
	  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\oauth2client.client", line 1936, in step2_exchange
	  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\httplib2", line 1593, in request
	  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\httplib2", line 1335, in _request
	  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\httplib2", line 1257, in _conn_request
	  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\httplib2", line 1021, in connect
	  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\httplib2", line 80, in _ssl_wrap_socket
	  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\ssl", line 891, in wrap_socket
	  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\ssl", line 507, in __init__
	IOError: [Errno 2] No such file or directory

	Z:\SOMEDIR>

Go to the gam-64 directory and run the same command; SUCCESS
	
	p:\gam-64>gam audit export status
	Current Export Requests:

	 Request ID: ...

**Comment by daubneyi** [comment]
+1, I have noticed the exact same issue with gam-64.

GAM 3.45 / Python 2.7.9 64-bit final / google-api-python-client 1.4.0 / Windows-8-6.2.9200 AMD64 (surface pro 3)
Path: C:\Program Files\gam-64\

```echo %path%```
```C:\windows\system32;C:\windows;......;C:\Program Files\gam-64\;...```

When running gam in any other directory gam brings up the **Select the authorized scopes for this token.** screen.

When my pwd is the **C:\Program Files\gam-64** directory all works fine.

**Comment by jay0lee** [comment]
Tested and fixed in GAM 3.5 (to be released real soon now).

**Comment by dtronolone** [comment]
Having same issue in 3.5, what this resolved?

**Comment by VerdonCollege** [comment]
Still having this issue, any idea when it will be fixed?

**Comment by VerdonCollege** [comment]
Just downloaded 3.61, this is still an issue.

**Comment by syntax53** [comment]
I just updated to GAM 3.62 and started having this problem.   I did not have it before then.

**Comment by Cameron-Roberts** [comment]
I'm also getting this on the latest version, GAM 3.62-Win-x64 running on Win7x64 so this one should probably be re-opened.
Thanks
