### ISSUE TITLE
GAM is too slow

### ISSUE THREAD

**Issue by prateekappviewx** [jay0lee/GAM#703]
Hi All,
I have been using GAM for quite a while now and we got it configured couple of years back and has been working without doing anything. However all of sudden our GAM has become very slow (extermely slow like it is taking 20-30 minutes to execute one command).
So i thought i would delete all keys etc and try again but still it is the same issue.
We havent upgraded our GAM past 1.5 years though
Anybody ever faced such issue before?
We are using multiple domains

**Comment by prateekappviewx** [comment]
Just now i downloaded and extracted the [GAM file] (https://github.com/jay0lee/GAM/releases) and copied to my GAM directory in linux server but still it is very slow not sure what could be the reason

**Comment by prateekappviewx** [comment]
ok actually on friday i ran command "gam oauth info" since it was very slow i left now today morning i see error as 

Traceback (most recent call last):
  File "gam.py", line 12881, in <module>
  File "gam.py", line 12074, in ProcessGAMCommand
  File "gam.py", line 423, in SetGlobalVariables
  File "gam.py", line 464, in doGAMCheckForUpdates
  File "httplib2/__init__.py", line 1659, in request
  File "httplib2/__init__.py", line 1399, in _request
  File "httplib2/__init__.py", line 1355, in _conn_request
  File "httplib.py", line 1108, in getresponse
httplib.ResponseNotReady

I have broken something after upgrade :(. .

Meanwhile i have created an empty test file noverifyssl.txt just to test but still commands are very slow :(. Will keep troubleshooting any help if highly appreciated.
Thanks

**Comment by prateekappviewx** [comment]
i have raised the same issue over google forum and now i am trying to reinstall from scratch. Can some on close the issue here.
In google forum the question has been asked here
https://groups.google.com/forum/#!topic/google-apps-manager/R2CisvoHCY8
