### ISSUE TITLE
Batch not working

### ISSUE THREAD

**Issue by peterleeman** [jay0lee/GAM#72]
Running v3.45 

Errors when running the batch command, with using CSV or TXT files.

Mac:

python gam.py batch /Users/peter/Desktop/jerome.txt 
Traceback (most recent call last):
  File "gam.py", line 7326, in <module>
    argv = shlex.split(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

Windows:

c:\gam>gam batch jerome.txt
Traceback (most recent call last):
  File "<string>", line 7326, in <module>
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\shlex", line
279, in split
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\shlex", line
269, in next
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\shlex", line
96, in get_token
  File "C:\Users\jlee\Documents\GitHub\GAM\build\gam\out00-PYZ.pyz\shlex", line
172, in read_token
ValueError: No closing quotation

**Comment by peterleeman** [comment]
This was resolved for me in v3.5
