### ISSUE TITLE
PY Error

### ISSUE THREAD

**Issue by ankiey** [jay0lee/GAM#768]
Hi,

I have installed GAM4.5 API over our system and created client secret outh accordingly.  I was able to run gam commands yesterday but since today's morning i am getting the below mentioned error ,it has happened earlier also , it works for a day and then it stops with the below attached error.

Is the Outh file getting expired after a session or the scope are being reset again?

Traceback (most recent call last):
  File "gam.py", line 12878, in <module>
  File "gam.py", line 12822, in ProcessGAMCommand
  File "gam.py", line 1523, in addDelegates
  File "oauth2client\transport.py", line 175, in new_request
  File "oauth2client\transport.py", line 282, in request
  File "httplib2\__init__.py", line 1694, in request
  File "httplib2\__init__.py", line 1434, in _request
  File "httplib2\__init__.py", line 1390, in _conn_request
  File "httplib.py", line 1108, in getresponse
httplib.ResponseNotReady
[63724] Failed to execute script gam

**Comment by jay0lee** [comment]
This is usually an issue with your local or network firewall or proxy. Please reach out on the Gam discussion group for help.
