### ISSUE TITLE
[3.5] Linux IOError

### ISSUE THREAD

**Issue by rinchen** [jay0lee/GAM#80]
Howdy, this issue is not present in 3.45.  In 3.5 when running commands in Ubuntu GNU/Linux I see abends with all commands.

$ ./gam.py info domain
Google Apps Domain: canonical.com
Traceback (most recent call last):
  File "./gam.py", line 8189, in <module>
    doGetDomainInfo()
  File "./gam.py", line 6294, in doGetDomainInfo
    result = callGAPI(service=cd.users(), function=u'list', fields=u'users(customerId)', customer=customerId, sortOrder=u'DESCENDING')
  File "./gam.py", line 379, in callGAPI
    return method(*_parameters).execute()
  File "/home/joey/GAM-3.5/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "/home/joey/GAM-3.5/googleapiclient/http.py", line 722, in execute
    body=self.body, headers=self.headers)
  File "/home/joey/GAM-3.5/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(_args, **kwargs)
  File "/home/joey/GAM-3.5/oauth2client/client.py", line 551, in new_request
    redirections, connection_type)
  File "/home/joey/GAM-3.5/httplib2/**init**.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/joey/GAM-3.5/httplib2/__init__.py", line 1411, in _request
    _updateCache(headers, response, content, self.cache, cachekey)
  File "/home/joey/GAM-3.5/httplib2/__init__.py", line 448, in _updateCache
    cache.set(cachekey, text)
  File "/home/joey/GAM-3.5/httplib2/__init__.py", line 715, in set
    f = file(cacheFullPath, "wb")
IOError: [Errno 36] File name too long: u'/home/joey/GAM-3.5/gamcache/www.googleapis.com,admin,directory,v1,users,customer=my_customer&fields=users%28customerId%29&alt=json&sortOrder=DESCENDING&prettyPrint=false,49ab63bcf113abad2621b2b9a5c62371'

**Comment by ticoombs** [comment]
Bump. Having the Exact same issue after syncing with master. 

```
python gam.py info domain
Google Apps Domain: domain.com
Traceback (most recent call last):
  File "gam.py", line 8715, in <module>
    doGetDomainInfo()
  File "gam.py", line 1148, in doGetDomainInfo
    doGetInstanceInfo()
  File "gam.py", line 6705, in doGetInstanceInfo
    result = callGAPI(service=cd.users(), function=u'list', fields=u'users(customerId)', customer=customerId, maxResults=1)
  File "gam.py", line 343, in callGAPI
    return method(**parameters).execute()
  File "/home/USER/Documents/Repos/GAM/src/oauth2client/util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/USER/Documents/Repos/GAM/src/googleapiclient/http.py", line 722, in execute
    body=self.body, headers=self.headers)
  File "/home/USER/Documents/Repos/GAM/src/oauth2client/client.py", line 589, in new_request
    redirections, connection_type)
  File "/home/USER/Documents/Repos/GAM/src/httplib2/__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/USER/Documents/Repos/GAM/src/httplib2/__init__.py", line 1412, in _request
    _updateCache(headers, response, content, self.cache, cachekey)
  File "/home/USER/Documents/Repos/GAM/src/httplib2/__init__.py", line 448, in _updateCache
    cache.set(cachekey, text)
  File "/home/USER/Documents/Repos/GAM/src/httplib2/__init__.py", line 715, in set
    f = file(cacheFullPath, "wb")
IOError: [Errno 36] File name too long: u'/home/USER/Documents/Repos/GAM/src/gamcache/www.googleapis.com,admin,directory,v1,users,customer=my_customer&fields=users%28customerId%29&alt=json&prettyPrint=false&maxResults=1,32CHARMD500000000000000000000000'
```
```
user% python 
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> len('/home/USER/Documents/Repos/GAM/src/gamcache/www.googleapis.com,admin,directory,v1,users,customer=my_customer&fields=users%28customerId%29&alt=json&prettyPrint=false&maxResults=1,32CHARMD500000000000000000000000')
210
>>> 
```

**Comment by ticoombs** [comment]
Please close issue. 

It is now resolved.
