### ISSUE TITLE
GAM Update - not correct on macOS 10.14.5 - Now I get errors and cannot work

### ISSUE THREAD

**Issue by oscarstv** [jay0lee/GAM#952]
Just updated from GAM 4.85 to 4.86.

When I try to delete a message (the reason for which I installed GAM), I get:
`Traceback (most recent call last):
  File "gam.py", line 14441, in <module>
  File "gam.py", line 14121, in ProcessGAMCommand
  File "gam.py", line 12657, in getUsersToModify
  File "gam.py", line 1336, in buildGAPIObject
  File "gam.py", line 9748, in _getValueFromOAuth
  File "site-packages/google/oauth2/id_token.py", line 141, in verify_oauth2_token
  File "site-packages/google/oauth2/id_token.py", line 122, in verify_token
  File "site-packages/google/auth/jwt.py", line 219, in decode
  File "site-packages/google/auth/jwt.py", line 128, in _unverified_decode
  File "site-packages/google/auth/_helpers.py", line 105, in to_bytes`

I updated it with the command: `bash <(curl -s -S -L https://git.io/install-gam) -l
`
If I type `gam version`
I get
`GAM 4.86 - https://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 3.7.3 64-bit final
google-api-python-client 1.7.8
Darwin-18.6.0-x86_64-i386-64bit x86_64
Path: /Users/Apple/bin/gam`

Thank you very much

**Comment by oscarstv** [comment]
Solved, reinstalling it, sorry!
